### ISSUE TITLE
Mejores practicas en nombramiento de campos

### ISSUE THREAD

**Issue by zgudino** [shelsxacm/movies-db#1]
Hola,

**Muy buen** proyecto primero que todo :clap:. Sin embargo, noto algunas inconsistencia en el nombramiento de los campos.

Recomiendo revisar esta excelente [guía](http://www.sqlstyle.guide) por **Simon Holywell**. Personalmente la uso en mi día a día.

**Comment by zgudino** [comment]
i.e, Tablas `Salas` y `Películas`. En vez de,

``` sql
CREATE TABLE Salas(
idSalas INT PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(100),
Pelicula INT,
idPeliculas INT,
FOREIGN KEY (idPeliculas) REFERENCES Peliculas(idPeliculas)
); 

CREATE TABLE Peliculas(
idPeliculas INT PRIMARY KEY AUTO_INCREMENT,
Nombre VARCHAR(100),
clfEdad VARCHAR(50)
);
```

recomiendo este,

``` sql
CREATE TABLE Salas(
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100),
pelicula_id INT,
FOREIGN KEY (pelicula_id) REFERENCES Peliculas(id)
);

CREATE TABLE Peliculas(
id INT PRIMARY KEY AUTO_INCREMENT,
nombre VARCHAR(100),
mpaa VARCHAR(50)
);
```

Varios temas:
1. Evitas DRY - Lines [10-11](https://github.com/shelsxacm/movies-db/blob/master/db/moviesdb.sql#L10-L11)
2. Auto descriptivas

**Comment by missdaemon** [comment]
@zgudino gracias por el advice, means a lot.
